/*
  Quà Việt Illustrator Template JSON Exporter

  Option A workflow:
  - Use one Illustrator artboard at the real production size of the editable area.
  - Example: a plaque plate that is 180 mm x 130 mm should have a 180 mm x 130 mm artboard.
  - Place/draw only the personalization overlay objects on this artboard.
  - Name rectangles in the Layers panel with these patterns:

      surface:main_plate
      field:logo:image
      field:organization:text:fontSize=8:align=center
      field:title:text:fontSize=13:align=center
      field:recipient:text:fontSize=11:align=center
      field:message:text:fontSize=7:align=center
      field:date:text:fontSize=7:align=center

  - Run this script from Illustrator: File > Scripts > Other Script...
  - The script writes an app-compatible JSON adjustment file.

  Coordinate model:
  - Illustrator/artboard geometry is exported in exact millimeters for production.
  - Preview x/y/width/height is generated by mapping real millimeters into the preview surface.
  - The app can render a customer preview from preview coordinates and production SVG from real millimeter coordinates.
*/

#target illustrator

(function () {
  if (app.documents.length === 0) {
    alert("Open an Illustrator document before exporting.");
    return;
  }

  var doc = app.activeDocument;
  var artboardIndex = doc.artboards.getActiveArtboardIndex();
  var artboard = doc.artboards[artboardIndex];
  var artboardRect = artboard.artboardRect; // [left, top, right, bottom] in points.
  var artLeft = artboardRect[0];
  var artTop = artboardRect[1];
  var artRight = artboardRect[2];
  var artBottom = artboardRect[3];
  var artWidthPt = artRight - artLeft;
  var artHeightPt = artTop - artBottom;
  var ptToMm = 25.4 / 72;

  var sku = prompt("SKU", doc.name.replace(/\.[^\.]+$/, ""));
  if (!sku) return;

  var templateId = prompt("Template ID", "tpl-" + sku.toLowerCase().replace(/[^a-z0-9]+/g, "-") + "-classic");
  if (!templateId) return;

  var productType = prompt("Product type: plaque, award, medal, trophy", "plaque");
  if (!productType) return;

  var mockupImageUrl = prompt("Mockup image URL", "/products/" + sku + ".jpg");
  if (!mockupImageUrl) return;

  var previewSurfaceX = numberPrompt("Preview surface x", 320);
  var previewSurfaceY = numberPrompt("Preview surface y", 310);
  var previewSurfaceWidth = numberPrompt("Preview surface width", 360);
  var previewSurfaceHeight = numberPrompt("Preview surface height", 280);
  var safeMarginMm = numberPrompt("Safe margin mm", 6);

  var realWidthMm = roundMm(artWidthPt * ptToMm);
  var realHeightMm = roundMm(artHeightPt * ptToMm);
  var surfaceId = "main_plate";
  var surfaceLabel = "Main Plate";
  var fields = [];

  walkItems(doc.pageItems, function (item) {
    if (!item.name) return;
    if (item.locked || item.hidden) return;

    var parts = item.name.split(":");
    if (parts[0] === "surface" && parts[1]) {
      surfaceId = cleanId(parts[1]);
      surfaceLabel = labelFromId(surfaceId);
      return;
    }

    if (parts[0] !== "field" || !parts[1]) return;

    var fieldId = cleanId(parts[1]);
    var fieldType = cleanId(parts[2] || "text");
    if (fieldType !== "image" && fieldType !== "text" && fieldType !== "textArc" && fieldType !== "asset") {
      fieldType = "text";
    }

    var bounds = boundsInArtboardMm(item);
    var meta = parseMeta(parts);
    var fontSizeMm = meta.fontSize ? Number(meta.fontSize) : defaultFontSizeMm(bounds.height);
    var preview = previewFromReal(bounds, fieldType, fontSizeMm);
    var fontSizePreview = Math.round((fontSizeMm / realHeightMm) * previewSurfaceHeight);

    var field = {
      id: fieldId,
      surfaceId: surfaceId,
      type: fieldType,
      label: meta.label || labelFromId(fieldId),
      x: preview.x,
      y: preview.y,
      width: preview.width,
      height: preview.height,
      realXmm: preview.realXmm,
      realYmm: preview.realYmm,
      realWidthMm: bounds.width,
      realHeightMm: bounds.height,
      editable: true
    };

    if (fieldType === "text" || fieldType === "textArc") {
      field.defaultValue = meta.defaultValue || field.label;
      field.fontSize = fontSizePreview;
      field.realFontSizeMm = fontSizeMm;
      field.fontFamilyId = meta.fontFamilyId || "clean-vietnamese";
      field.fontWeight = meta.fontWeight || "700";
      field.align = meta.align || "center";
      field.colorToken = meta.colorToken || "primaryText";
      field.maxLength = meta.maxLength ? Number(meta.maxLength) : 60;
      field.required = meta.required === "false" ? false : true;
      if (meta.optional === "true") field.optional = true;
    } else if (fieldType === "image") {
      field.optional = meta.optional === "false" ? false : true;
    }

    fields.push(field);
  });

  if (fields.length === 0) {
    alert("No fields found. Name rectangles like field:recipient:text or field:logo:image.");
    return;
  }

  fields.sort(function (a, b) {
    return a.realYmm === b.realYmm ? a.realXmm - b.realXmm : a.realYmm - b.realYmm;
  });

  var adjustment = {
    version: 1,
    sku: sku,
    templateId: templateId,
    mockupImageUrl: mockupImageUrl,
    previewCanvas: {
      width: 1000,
      height: 1000
    },
    surfaces: [
      {
        id: surfaceId,
        type: "rectangle",
        label: surfaceLabel,
        x: previewSurfaceX,
        y: previewSurfaceY,
        width: previewSurfaceWidth,
        height: previewSurfaceHeight,
        realWidthMm: realWidthMm,
        realHeightMm: realHeightMm,
        safeMarginMm: safeMarginMm
      }
    ],
    fields: fields,
    illustratorExport: {
      mode: "real-size-artboard",
      artboardWidthMm: realWidthMm,
      artboardHeightMm: realHeightMm,
      sourceDocument: doc.name,
      exportedAt: isoNow()
    },
    updatedAt: isoNow()
  };

  var file = File.saveDialog("Save Quà Việt template JSON", "*.json");
  if (!file) return;
  file.encoding = "UTF-8";
  file.open("w");
  file.write(stringify(adjustment, 0));
  file.close();

  alert("Exported " + fields.length + " fields for " + sku + ".\nReal size: " + realWidthMm + " mm x " + realHeightMm + " mm.");

  function numberPrompt(label, fallback) {
    var value = prompt(label, String(fallback));
    if (value === null) throw new Error("Export cancelled.");
    var parsed = Number(value);
    return isFinite(parsed) ? parsed : fallback;
  }

  function walkItems(items, visitor) {
    for (var i = 0; i < items.length; i += 1) {
      visitor(items[i]);
    }
  }

  function boundsInArtboardMm(item) {
    var b = item.geometricBounds; // [left, top, right, bottom] in points.
    var left = (b[0] - artLeft) * ptToMm;
    var top = (artTop - b[1]) * ptToMm;
    var right = (b[2] - artLeft) * ptToMm;
    var bottom = (artTop - b[3]) * ptToMm;
    return {
      x: roundMm(left),
      y: roundMm(top),
      width: roundMm(right - left),
      height: roundMm(bottom - top)
    };
  }

  function previewFromReal(bounds, fieldType, fontSizeMm) {
    var previewX = previewSurfaceX + (bounds.x / realWidthMm) * previewSurfaceWidth;
    var previewY = previewSurfaceY + (bounds.y / realHeightMm) * previewSurfaceHeight;
    var previewWidth = (bounds.width / realWidthMm) * previewSurfaceWidth;
    var previewHeight = (bounds.height / realHeightMm) * previewSurfaceHeight;

    if (fieldType === "image") {
      return {
        x: Math.round(previewX),
        y: Math.round(previewY),
        width: Math.round(previewWidth),
        height: Math.round(previewHeight),
        realXmm: bounds.x,
        realYmm: bounds.y
      };
    }

    return {
      x: Math.round(previewX + previewWidth / 2),
      y: Math.round(previewY + ((fontSizeMm / realHeightMm) * previewSurfaceHeight)),
      width: Math.round(previewWidth),
      height: Math.round(previewHeight),
      realXmm: roundMm(bounds.x + bounds.width / 2),
      realYmm: roundMm(bounds.y + fontSizeMm)
    };
  }

  function parseMeta(parts) {
    var meta = {};
    for (var i = 3; i < parts.length; i += 1) {
      var pair = parts[i].split("=");
      if (pair.length === 2) meta[cleanId(pair[0])] = pair[1];
    }
    return meta;
  }

  function cleanId(value) {
    return String(value).replace(/^\s+|\s+$/g, "");
  }

  function labelFromId(value) {
    var label = String(value).replace(/[_-]+/g, " ");
    return label.charAt(0).toUpperCase() + label.slice(1);
  }

  function defaultFontSizeMm(heightMm) {
    return roundMm(Math.max(3, heightMm * 0.42));
  }

  function roundMm(value) {
    return Math.round(value * 1000) / 1000;
  }

  function isoNow() {
    return new Date().toISOString();
  }

  function stringify(value, depth) {
    var indent = repeat("  ", depth);
    var nextIndent = repeat("  ", depth + 1);
    var key;
    var i;

    if (value === null) return "null";
    if (typeof value === "number" || typeof value === "boolean") return String(value);
    if (typeof value === "string") return quote(value);
    if (value instanceof Array) {
      if (value.length === 0) return "[]";
      var arrayParts = [];
      for (i = 0; i < value.length; i += 1) {
        arrayParts.push(nextIndent + stringify(value[i], depth + 1));
      }
      return "[\n" + arrayParts.join(",\n") + "\n" + indent + "]";
    }
    var objectParts = [];
    for (key in value) {
      if (value.hasOwnProperty(key) && value[key] !== undefined) {
        objectParts.push(nextIndent + quote(key) + ": " + stringify(value[key], depth + 1));
      }
    }
    if (objectParts.length === 0) return "{}";
    return "{\n" + objectParts.join(",\n") + "\n" + indent + "}";
  }

  function quote(value) {
    return "\"" + String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\r/g, "\\r").replace(/\n/g, "\\n") + "\"";
  }

  function repeat(text, count) {
    var output = "";
    for (var i = 0; i < count; i += 1) output += text;
    return output;
  }
})();
